name: CI/CD to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Grant execute permissions for gradlew
        run: chmod +x gradlew

      - name: Build and Test
        run: ./gradlew build

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to AWS EC2
        env:
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}
          PEM_KEY: ${{ secrets.EC2_PEM_KEY }}
        run: |
          echo -e "$PEM_KEY" > deploy_key.pem
          chmod 600 deploy_key.pem
          scp -i deploy_key.pem ./path-to-your-file-or-directory $USER@$HOST:/path-on-ec2
          rm -f deploy_key.pem
